dog:
  aem:
    schema: https
    port: 443
  name: Cookie
  breed: Golden Retriever

cat:
  cat_id: 1
  cat_name: Cherry
  cat_breed: White
 
---

spring: 
  config:
    activate:
      on-profile: 'test'
  dog:
    colour: Golden Brown 

---

spring: 
  config:
    activate:
      on-profile: 'dev'
  dog:
    colour: White
    aem:
      host: hostname
      authorHost: devAuthor
  cat:
    cat_legs: 4

---
